@baseUrl = https://asia-south1-theta-outrider-310911.cloudfunctions.net
# @baseUrl = http://localhost:8080/
###
POST {{baseUrl}}/upload-test
Content-Type: application/json
Authorization: dGVzdEA5OTg=

{
  "examInfo": {
    "exams": ["NTA NET"],
    "category": "William Shakespeare",
    "testName": "Shakespere Hamlet DST 7",
    "timeLimit": 60,
    "negitiveMarking": true,
    "totalQuestions": 10
  },
  "questions": [
    {
      "N": 1,
      "Q": "What was the name of the imaginary village created by Christopher Isherwood along with his friend and long term associate Edward Upward?",
      "O": ["Potteries", "Mortmere", "Hertford", "Anglishian"],
      "A": 1,
      "S": ""
    },
    {
      "N": 2,
      "Q": "With whom did Christopher Isherwood enjoy a friendship who also served as the inspiration for the work Mr Norris Changes Trains?",
      "O": ["Edward Upward", "W.H Auden", "Gerald Hamilton", "Stephen Spender"],
      "A": 2,
      "S": ""
    },
    {
      "N": 3,
      "Q": "To which country did Christopher Isherwood flee to along with his friend in the peak year of 1933?",
      "O": ["Greece", "Rome", "Russia", "China"],
      "A": 0,
      "S": ""
    }
  ]
}

###
POST {{baseUrl}}/send-result
Content-Type: application/json

{
  "testId": "sss-12",
  "response": {
    "name": "Shivam Kumar Jha 4",
    "correctAns": 12,
    "percentage": 50,
    "time": 120
  }
}

###
GET {{baseUrl}}/get-result?testId=shakespere-hamlet-dst-5

###
OPTIONS {{baseUrl}}/upload-test

###
GET https://storage.googleapis.com/mcq-test/billing-notification.json
Origin: http://localhost:3000
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
