const EXAMS = [
  { label: "NET/SET", value: "NET/SET" },
  { label: "UP PGT", value: "UP PGT" },
  { label: "UP GIC", value: "UP GIC" },
  { label: "UP Junior Asst, Teacher", value: "UP Junior Asst, Teacher" },
  { label: "UP TGT", value: "UP TGT" },
  { label: "KVS/NVS PGT/TGT", value: "KVS/NVS PGT/TGT" },
  { label: "DSSB PGT/TGT", value: "DSSB PGT/TGT" },
  { label: "Uttrakhand L.T Grade", value: "Uttrakhand L.T Grade" },
  { label: "UP GIC L.T Grade", value: "UP GIC L.T Grade" },
  { label: "Uttrakhand PGT", value: "Uttrakhand PGT" },
  { label: "UPHESC (Asst. Prof.)", value: "UPHESC (Asst. Prof.)" },
];

const CATEGORIES = [
  "Shakespeare",
  "Milton",
  "WordsWorth",
  "Robert Frost",
  "John Keats",
  "Walt Whitman",
  "P.B Shelley",
  "A.L Tennyson",
  "Matthew Arnold",
  "T.S Eliot",
  "W.B Yeats",
  "Pope",
  "Dry den",
  "Wren & Martin Grammar",
  "Word Power Made Easy",
  "Dilip Kushwaha Word Power",
  "Black Book Word Power",
  "Grammar",
  "Vocabulary",
  "Lucent Grammar",
  "S.P Bakshi Grammar",
  "Background to Eng Lit. (B. Prasad)",
  "Indian Literature",
  "American Literature",
  "British Literature",
  "Criticism & Theory",
  "New / Post-colonial Literature",
  "World Literature",
  "Literary Forms / Terms / Prosody / Rhetoric",
  "Literary Ages / Movements",
];

export { EXAMS, CATEGORIES };
